### ISSUE TITLE
Issue with sonarbit dependency

### ISSUE THREAD

**Issue by microbit-mark** [tinkertanker/pxt-motorbit#4]
When adding the motorbit extension, occasionaly the sonarbit dependency is not added.

If you try to update it, you end up with conflicting versions 1.03 and 1.04

![image](https://user-images.githubusercontent.com/31242877/94569463-a6e65f00-0265-11eb-92a5-6179159e569f.png)

The depedency targets v1.03
https://github.com/tinkertanker/pxt-motorbit/blob/3aa73f985b1a65acf5df61c0608b2884bfade671/pxt.json#L8

But the current version is 2.00
https://github.com/elecfreaks/pxt-sonarbit/blob/7e1e37b13a65df19f2a92503d8bfa7869632da1b/pxt.json#L3

Does this need updating?

**Comment by microbit-mark** [comment]
^ @yjsoon @lionyhw

**Comment by lionyhw** [comment]
It's fixed. Thank you.
